In [3]:
import pandas as pd
df = "Resources/us-counties.csv"
df1 = pd.read_csv(df)
file = "Resources/county_mask_mandate_data.xlsx"
df2 = pd.read_excel(file)

## Read in Both Datasets

In [4]:
df1.head()

         date     county       state     fips  cases  deaths
0  2020-01-21  Snohomish  Washington  53061.0      1     0.0
1  2020-01-22  Snohomish  Washington  53061.0      1     0.0
2  2020-01-23  Snohomish  Washington  53061.0      1     0.0
3  2020-01-24       Cook    Illinois  17031.0      1     0.0
4  2020-01-24  Snohomish  Washington  53061.0      1     0.0

In [6]:
#Shows the data types for the df1
df1.dtypes

date       object
county     object
state      object
fips      float64
cases       int64
deaths    float64
dtype: object

In [10]:
# count the number of rows with empty columns
count = df1['fips'].isna().sum()
print(count)

19744

In [11]:
#count the number of rows with data in each column
df1.count()

date      2135147
county    2135147
state     2135147
fips      2115403
cases     2135147
deaths    2086356
dtype: int64

In [15]:
# Drop the rows with blank data creating a new dataframe
df1_clean = df1.dropna()

In [16]:
# count the number of rows with data in each column from the clean dataframe
df1_clean.count()

date      2066612
county    2066612
state     2066612
fips      2066612
cases     2066612
deaths    2066612
dtype: int64

In [19]:
#change fips from float64 to int64 to match datatype of df1_clean "county_fips"
df1_clean['fips'].astype('int64')

0          53061
1          53061
2          53061
3          17031
4          53061
           ...
2135142    56037
2135143    56039
2135144    56041
2135145    56043
2135146    56045
Name: fips, Length: 2066612, dtype: int64

In [20]:
# change deaths from float64 to int64 to match datatype of df1_clean "deaths"
df1_clean['deaths'].astype('int64')

0            0
1            0
2            0
3            0
4            0
          ...
2135142    114
2135143     14
2135144     34
2135145     41
2135146     16
Name: deaths, Length: 2066612, dtype: int64

In [3]:
df2.head()

,state_fips,state_name,county_fips,county_name,county_start_date,county_end_date,county_conditions,county_source,escalation,defiance,county_start_edate,state_start_date,state_end_date,state_conditions,state_source,state_start_edate,earliest_start_edate,county_fips_string,earliest_start_date
0,1,ALABAMA,1067,Henry County,NaT,NaN,NaN,NaN,NaN,NaN,NaN,07/16/2020,07/31/2020,all public places,https://www.alabamapublichealth.gov/legal/asse...,22112.0,22112.0,1067,7-16-2020
1,1,ALABAMA,1071,Jackson County,2020-07-01,NaN,all public places,https://www.examiner.net/news/20200629/jackson...,NaN,NaN,22097.0,07/16/2020,07/31/2020,all public places,https://www.alabamapublichealth.gov/legal/asse...,22112.0,22097.0,1071,7-1-2020
2,1,ALABAMA,1093,Marion County,2020-07-09,NaN,retail only,https://fox59.com/news/coronavirus/starting-to...,NaN,NaN,22105.0,07/16/2020,07/31/2020,all public places,https://www.alabamapublichealth.gov/legal/asse...,22112.0,22105.0,1093,7-9-2020
3,1,ALABAMA,1073,Jefferson County,2020-06-29,NaN,all public places,https://www.wbrc.com/2020/06/29/jefferson-coun...,NaN,NaN,22095.0,07/16/2020,07/31/2020,all public places,https://www.alabamapublichealth.gov/legal/asse...,22112.0,22095.0,1073,6-29-2020
4,1,ALABAMA,1099,Monroe County,NaT,NaN,NaN,NaN,NaN,NaN,NaN,07/16/2020,07/31/2020,all public places,https://www.alabamapublichealth.gov/legal/asse...,22112.0,22112.0,1099,7-16-2020

In [7]:
df2.dtypes

state_fips                       int64
state_name                      object
county_fips                      int64
county_name                     object
county_start_date       datetime64[ns]
county_end_date                 object
county_conditions               object
county_source                   object
escalation                      object
defiance                        object
county_start_edate             float64
state_start_date                object
state_end_date                  object
state_conditions                object
state_source                    object
state_start_edate              float64
earliest_start_edate           float64
county_fips_string               int64
earliest_start_date             object
dtype: object

## Filter to show only Tennessee in both Datasets

In [4]:
df2["state_name"] = "Tennessee"

In [5]:
df2.head()

,state_fips,state_name,county_fips,county_name,county_start_date,county_end_date,county_conditions,county_source,escalation,defiance,county_start_edate,state_start_date,state_end_date,state_conditions,state_source,state_start_edate,earliest_start_edate,county_fips_string,earliest_start_date
0,1,Tennessee,1067,Henry County,NaT,NaN,NaN,NaN,NaN,NaN,NaN,07/16/2020,07/31/2020,all public places,https://www.alabamapublichealth.gov/legal/asse...,22112.0,22112.0,1067,7-16-2020
1,1,Tennessee,1071,Jackson County,2020-07-01,NaN,all public places,https://www.examiner.net/news/20200629/jackson...,NaN,NaN,22097.0,07/16/2020,07/31/2020,all public places,https://www.alabamapublichealth.gov/legal/asse...,22112.0,22097.0,1071,7-1-2020
2,1,Tennessee,1093,Marion County,2020-07-09,NaN,retail only,https://fox59.com/news/coronavirus/starting-to...,NaN,NaN,22105.0,07/16/2020,07/31/2020,all public places,https://www.alabamapublichealth.gov/legal/asse...,22112.0,22105.0,1093,7-9-2020
3,1,Tennessee,1073,Jefferson County,2020-06-29,NaN,all public places,https://www.wbrc.com/2020/06/29/jefferson-coun...,NaN,NaN,22095.0,07/16/2020,07/31/2020,all public places,https://www.alabamapublichealth.gov/legal/asse...,22112.0,22095.0,1073,6-29-2020
4,1,Tennessee,1099,Monroe County,NaT,NaN,NaN,NaN,NaN,NaN,NaN,07/16/2020,07/31/2020,all public places,https://www.alabamapublichealth.gov/legal/asse...,22112.0,22112.0,1099,7-16-2020

In [ ]:
df2